trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'

- stage: Deploy
  jobs:
  - deployment: DeployToDev
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Application Deployed Successfully"